/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        tertiary: '#041428',
        'primary-fixed-dim': '#bcc7de',
        'on-tertiary-container': '#8190a9',
        error: '#ba1a1a',
        'surface-tint': '#545f73',
        'outline-variant': '#c5c6cd',
        'on-primary-fixed': '#111c2d',
        'inverse-on-surface': '#eef1f3',
        'primary-fixed': '#d8e3fb',
        'surface-variant': '#e0e3e5',
        'on-error-container': '#93000a',
        'surface-bright': '#f7fafc',
        'secondary-container': '#0171e8',
        'on-primary-fixed-variant': '#3c475a',
        'surface-container-low': '#f1f4f6',
        'tertiary-fixed': '#d4e3ff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'on-error': '#ffffff',
        'surface-container-high': '#e5e9eb',
        'secondary-fixed': '#d7e2ff',
        'on-secondary-fixed': '#001a40',
        'error-container': '#ffdad6',
        primary: '#091426',
        outline: '#75777d',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed': '#0c1c30',
        'surface-container': '#ebeef0',
        'surface-dim': '#d7dadc',
        'on-secondary-container': '#fefcff',
        'primary-container': '#1e293b',
        'on-primary': '#ffffff',
        'tertiary-container': '#1a293e',
        'on-primary-container': '#8590a6',
        'on-background': '#181c1e',
        'on-secondary-fixed-variant': '#004491',
        secondary: '#0059ba',
        'on-surface': '#181c1e',
        surface: '#f7fafc',
        'on-surface-variant': '#45474c',
        'on-secondary': '#ffffff',
        background: '#f7fafc',
        'tertiary-fixed-dim': '#b8c7e2',
        'inverse-primary': '#bcc7de',
        'secondary-fixed-dim': '#acc7ff',
        'on-tertiary-fixed-variant': '#39485e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },

  plugins: [],
};
